### ISSUE TITLE
"TypeError: fs.rmSync is not a function" on quit with remove

### ISSUE THREAD

**Issue by DavidWells** [mhlabs/cfn-diagram#35]
Hey, great utility!

I found a small error when running quit the remove option set to true.

```
? Do you want to keep your diagram? No
(node:13514) UnhandledPromiseRejectionWarning: TypeError: fs.rmSync is not a function
    at Object.generate (/Users/x/node_modules/@mhlabs/cfn-diagram/graph/MxGenerator.js:345:14)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Command.<anonymous> (/Users/x/node_modules/@mhlabs/cfn-diagram/commands/draw.io/index.js:36:5)
(node:13514) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13514) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Should `fs.rmSync` be `fs.unlinkSync` [here](https://github.com/mhlabs/cfn-diagram/blob/9175c7c9e5e760a3c23a4cdc30c9104ffaa9e3b8/graph/MxGenerator.js#L345)? 

Error seen in node v12.7.0

**Comment by ljacobsson** [comment]
Hey @DavidWells! Glad you like it :-)

Thanks for reporting. Looks like `rmSync` is a new addition to nodejs. 

I'm changing this to use `unlinkSync` which afaik does the same thing.
