### ISSUE TITLE
Receiving UnhandledPromiseRejectionWarning Error

### ISSUE THREAD

**Issue by rhs615** [mhlabs/cfn-diagram#39]
```
(node:18865) UnhandledPromiseRejectionWarning: TypeError: joinList.filter is not a function
    at createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:9:18)
    at createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:36:7)
    at createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:36:7)
    at createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:36:7)
    at createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:36:7)
    at createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:36:7)
    at createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:36:7)
    at Object.createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:36:7)
    at makeGraph (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/graph/Vis.js:32:12)
    at Object.renderTemplate (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/graph/Vis.js:184:28)
(node:18865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18865) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rhs615** [comment]
Seems to be specific to the CFT being used
