### ISSUE TITLE
TypeError: joinList.filter is not a function

### ISSUE THREAD

**Issue by asifiqbal** [mhlabs/cfn-diagram#41]
I am getting another error. Not sure if it related to my previous issue about npm warn

```
~ → cfn-dia draw.io -t quickstart-atlassian-jira/templates/quickstart-jira-dc-with-vpc.template.yaml
/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:9
        joinList.filter(
                 ^

TypeError: joinList.filter is not a function
    at createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:9:18)
    at createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:36:7)
    at createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:36:7)
    at Object.createPseudoResources (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:36:7)
    at Object.generate (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/graph/MxGenerator.js:244:12)
    at Command.<anonymous> (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/commands/draw.io/index.js:37:23)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/usr/local/lib/node_modules/@mhlabs/cfn-diagram/node_modules/commander/index.js:1460:12)
```

Here is the template

https://github.com/aws-quickstart/quickstart-atlassian-jira/blob/main/templates/quickstart-jira-dc-with-vpc.template.yaml

**Comment by robbrad** [comment]
Seeing this issue as well

Cause by CF: !Join ["", !Split ["-", !GetAtt EFSFileSystem.FileSystemId]]

**Comment by kazanglenn** [comment]
I hit this problem when working with complex nested stacks.

I resolved the error locally by updating **JsonUtil.js** line 7, in `createPseudoResources`, to be 

`const joinList = [].concat(current[k]["Fn::Join"][1]);`

as joinList is assumed to be an array, but there may not be elements to fill it.

With this change in place all the diagrams I required were generated without error.
