### ISSUE TITLE
Expects cdk.out/STACK_NAME.assets.template.json to exist after synth

### ISSUE THREAD

**Issue by l0b0** [mhlabs/cfn-diagram#42]
Running `cfn-dia html --ci-mode` results in the following error message:

```text
$ cfn-dia html --ci-mode 
Bundling asset project/proccessing_lambda_function/Code/Stage...
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'cdk.out/STACK_NAME.assets.template.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at fromCDK ([…]/node_modules/@mhlabs/cfn-diagram/shared/templateParser.js:95:30)
    at Object.get ([…]/node_modules/@mhlabs/cfn-diagram/shared/templateParser.js:31:16)
    at Command.<anonymous> ([…]/node_modules/@mhlabs/cfn-diagram/commands/html/index.js:29:34)
    at Command.listener [as _actionHandler] ([…]/node_modules/commander/index.js:922:31)
    at Command._parseCommand ([…]/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand ([…]/node_modules/commander/index.js:1443:18)
    at Command._parseCommand ([…]/node_modules/commander/index.js:1460:12)
    at Command.parse ([…]/node_modules/commander/index.js:1292:10) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'cdk.out/STACK_NAME.assets.template.json'
}
```

Context:

```console
$ cfn-dia --vers
1.1.28
$ cdk --version
1.119.0 (build 2921d64)
```

**Comment by lewismc** [comment]
I'm getting the same result
```
cfn-dia --vers
1.1.33
cdk --version
2.21.1 (build a6ee543)
```
