### ISSUE TITLE
Unresolved promise error when running in WSL

### ISSUE THREAD

**Issue by tobilg** [mhlabs/cfn-diagram#9]
When trying to generate HTML output, I see the following error with version 1.1.2:

```bash
cfn-dia html -t .serverless/cloudformation-template-update-stack.json -o docs/stack.drawio

(node:2662) UnhandledPromiseRejectionWarning: Error: spawn wslvar ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:2662) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was 
not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2662) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tobilg** [comment]
Eventually https://stackoverflow.com/a/54515183/1603357 could help

**Comment by tobilg** [comment]
After installing https://github.com/wslutilities/wslu the problem disappeared. Seems to be the unsolved issue of https://github.com/sindresorhus/open/issues/198.

Maybe add a remark in the README? I can close the ticket if you like, it's not caused by cfn-dia.

**Comment by ljacobsson** [comment]
Thanks for investigating this. 

Let's leave this open and I'll update the readme when I get a chance.

Glad it works now :+1:

**Comment by ljacobsson** [comment]
Have added this info to the 'known issues' section of the readme.

Closing

**Comment by tobilg** [comment]
Thanks a lot @ljacobsson!
